version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.5

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}

      - run:
          name: Install
          command: npm i

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}

      # Run tests!
      - run:
          name: Test
          command: npm test
      - run:
          name: Dist
          command: npm run dist
